# Generated by Django 3.2.10 on 2022-07-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
